# Generated by Django 6.0.7 on 2026-07-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='V THILOTHAMA', max_length=100)),
                ('tagline', models.CharField(default='Full-Stack Developer', max_length=200)),
                ('description', models.TextField(default='A passionate Full-Stack Developer specializing in Python, Django, Java, and modern web technologies. I build clean, powerful, and aesthetically pleasing applications.')),
                ('badge_text', models.CharField(default='Available for Hire', max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('github_url', models.URLField(blank=True, default='https://github.com/thilluu129')),
                ('linkedin_url', models.URLField(blank=True, default='')),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('resume_url', models.URLField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Hero Content',
                'verbose_name_plural': 'Hero Content',
            },
        ),
    ]
